name: coles
num_iters: 5
mcc_vocab_size: 377
mcc_embed_size: 32
embed_noise: .005
hidden_size: 32
# 'gru' or 'lstm'
type: gru
data:
  min_len: 20
  split_count: 5
  seq_len: 40
learning_params:
  epochs: 50
  lr: .001
  weight_decay: .00005
  step_size: 30
  gamma: .9
  train_batch_size: 256
  val_batch_size: 256
  train_num_workers: 4
  val_num_workers: 4
  early_stopping:
    min_delta: .01
    patience: 5