name: tr2vec
window_size: 10
num_iters: 5
mcc_vocab_size: 377
mcc_embed_size: 16
data_split:
  test_fraq: .2
  val_frag: .2
learning_params:
  lr: .5
  lr_scheduler_params:
    factor: .5
    patience: 2
  batch_size: 2000
  max_epochs: 50
  early_stopping_params:
    min_delta: .001
    patience: 5
