#! /bin/bash

DOCKER_NAME="i.kuleshov"
DOCKER_USER_ID=1015 # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=1015
IMAGE_NAME="transaction_data_gen"
CONTAINER_PORT=8893 # used in launch_container file

