#! /bin/bash
source credentials

docker run \
 -d \
 -p ${CONTAINER_PORT}:8890 \
 --shm-size=8g \
 --memory=24g \
 --cpus=4 \
 --user ${DOCKER_USER_ID}:${DOCKER_GROUP_ID} \
 --name "${DOCKER_NAME}.${IMAGE_NAME}" \
 --rm -it --init \
 -v $(cd .. && pwd):/app \
 --gpus "device=0" \
 "${DOCKER_NAME}/${IMAGE_NAME}" bash
