_target_: src.networks.modules.VanillaAE
_partial_: True
loss_weights:
  mcc: 10
  amount: 1
encoder_weights: weights/coles_best_state_dict.pth
unfreeze_enc_after: 5
lr: .0001
weight_decay: 0.00005
mcc_vocab_size: 344
