defaults:
  - dataset: churn
  - encoder: coles_pretrained
  - decoder: lstm
  - module: vanilla
  - _self_

trainer_args:
  max_epochs: 50

datamodule_args:
  train_batch_size: 32
  valid_batch_size: 8
  train_num_workers: 4
  valid_num_workers: 4
