defaults:
  - dataset: churn
  - encoder: coles_pretrained
  - decoder: lstmcell
  - module: vanilla_pretrained
  - _self_

trainer_args:
  max_epochs: 50

train_dl_args:
  batch_size: 196
  num_workers: 4

val_dl_args:
  batch_size: 8
  num_workers: 4
