name: lstm
core:
  _target_: src.networks.autoencoder_core.NLPLSTM
  hidden_size: 256
  output_size: 256
  num_layers: 1
num_iters: 1
mcc_vocab_size: 377
loss_weights:
  - 1
  - 100
  - 1
freeze_embed: True
unfreeze_after: 5
use_user_embedding: True
user_embedding_size: 32
use_masked_prediction: True
rand_rate: .2
mask_token: -1

data_split:
  test_size: .2
  val_size: .2
tr2vec:
  window_size: 10
  mcc_embed_size: 32
learning_params:
  num_workers: 4
  lr: .003
  weight_decay: .00001
  lr_schedule_params:
    factor: .5
    patience: 2
  batch_size: 256
  max_epochs: 50
  early_stopping_params:
    min_delta: .001
    patience: 5