name: new_data
dir_path: data/new_data
ignore_existing_preproc: False
user_column: user_id
mcc_column: mcc_code
transaction_amt_column: transaction_amt
transaction_dttm_column: transaction_dttm
preproc:
  drop_currency: True
  time_delta: 3
  len_min: 20
  len_max: 90
anomaly_strategy: quantile
percentile: .95
